Completed Javascript typing tutor
heesoo-kim97/c0621-code-solutions pull request #57
Opened 2021-07-13 16:01 UTC by heesoo-kim97

<img width="1386" alt="Screen Shot 2021-07-13 at 8 58 56 AM" src="https://user-images.githubusercontent.com/82424354/125485863-b2d86a18-ee31-4551-a7a3-bd6dc1152d86.png">

2021-07-19 22:21 UTC, codingcodymiller requested changes

2021-07-19 22:21 UTC, codingcodymiller commented on javascript-typing-tutor/main.js
> +    $span[i].className = 'right';
So if it's the last letter, anything you type is right?

2021-08-11 00:05 UTC, thebearingedge requested changes

2021-08-11 00:05 UTC, thebearingedge commented on javascript-typing-tutor/main.js
> +    $span[i].className = 'right';
Instead of setting the className, just put a `return` in here. If `i === $span.length`, the game is over.

2021-08-12 21:52 UTC, thebearingedge approved these changes

2021-08-12 21:52 UTC, merged